import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="app">
      <div className="header">
        <h1>My Dashboard App</h1>
        <p>A beautiful admin dashboard</p>
      </div>

      <div className="content">
        <h2>Dashboard Overview</h2>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', marginTop: '24px' }}>
          <div className="card">
            <h3>Total Users</h3>
            <p style={{ fontSize: '32px', fontWeight: 'bold', color: '#4299e1', marginTop: '8px' }}>1,234</p>
          </div>

          <div className="card">
            <h3>Active Projects</h3>
            <p style={{ fontSize: '32px', fontWeight: 'bold', color: '#48bb78', marginTop: '8px' }}>42</p>
          </div>

          <div className="card">
            <h3>Tasks Completed</h3>
            <p style={{ fontSize: '32px', fontWeight: 'bold', color: '#ed8936', marginTop: '8px' }}>{count}</p>
            <button className="button" onClick={() => setCount(count + 1)} style={{ marginTop: '12px' }}>
              Complete Task
            </button>
          </div>
        </div>

        <div style={{ marginTop: '32px' }}>
          <h3>Recent Activity</h3>
          <div className="card">
            <p>✓ Project setup completed</p>
            <p style={{ color: '#718096', fontSize: '14px', marginTop: '4px' }}>Just now</p>
          </div>
          <div className="card">
            <p>✓ UI generated by Ralph</p>
            <p style={{ color: '#718096', fontSize: '14px', marginTop: '4px' }}>Just now</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default App
